package:
  name: nexpy
  version: "2.0.0"

source:
  git_url: https://github.com/nexpy/nexpy.git
  git_tag: v2.0.0

build:
  entry_points:
    - nexpy = nexpy.nexpygui:main
  number: 0
  noarch: generic

requirements:
  build:
    - python >=3.9
    - setuptools
    - setuptools_scm

  run:
    - python >= 3.9
    - ansi2html
    - fabio
    - h5py
    - ipython
    - lmfit
    - matplotlib
    - mplcursors
    - nexusformat >= 2.0.0b3
    - numpy
    - packaging
    - pillow
    - pygments
    - pylatexenc
    - qtconsole
    - qtpy
    - scipy

test:
  imports:
    - nexpy
    - nexpy.api
    - nexpy.api.frills
    - nexpy.api.frills.models
    - nexpy.definitions
    - nexpy.gui
    - nexpy.plugins
    - nexpy.readers

  commands:
    - nexpy --help

about:
  home: "http://nexpy.github.io/nexpy/"
  license: "BSD-3-Clause"
  license_family: "BSD"
  license_file: "COPYING"
  summary: "NeXpy: A Python GUI to analyze NeXus data"
  doc_url: "https://nexpy.github.io/nexpy/"
  dev_url: "https://github.com/nexpy/nexpy"
